name: Manual CodeQL Scan

on:
  workflow_dispatch:
    inputs:
      scan_target:
        description: '¿Qué rama deseas escanear?'
        required: true
        default: 'develop'
        type: string

jobs:
  analyze:
    name: Run CodeQL manually
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.scan_target }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run CodeQL
        uses: codebeltnet/codeql-scan@v1.0.0
        with:
          languages: python
          build-mode: none
